config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  get 'notifications/index'

  resources :poems, only: [:index, :show]

  resources :my_page, only: [:index]

  root 'top#index'

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :tasks

  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  #has_many :blogs, foreign_key: user_id
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  has_many :tasks, dependent: :destroy
  #has_many :charges, class_name: 'Task'

  has_many :submit_requests, dependent: :destroy
  has_many :received_requests, class_name: 'SubmitRequest'#, foreign_key: 'request_user_id'

  def following?(user)
    self.relationships.find_by(followed_id: user.id)
  end

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    self.relationships.find_by(followed_id: other_user.id).destroy!
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",#QA: Uniqueでindex定義があるからこうするっぽい
        image_url: auth.info.image,
        password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save(validate: false)#validateしないとはなぜあえて？
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
   user = User.find_by(provider: auth.provider, uid: auth.uid)
   unless user
     user = User.new(
         name:     auth.info.nickname,
         image_url: auth.info.image,
         provider: auth.provider,
         uid:      auth.uid,
         email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
         password: Devise.friendly_token[0, 20]
     )
     user.skip_confirmation!
     user.save
   end
   user
 end

 def self.create_unique_string
   SecureRandom.uuid
 end

 def update_with_password(params, *options)
   if provider.blank?
     super
   else
     params.delete :current_password
     update_without_password(params, *options)
   end
 end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    #binding.pry
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <br>
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id),remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(follower_id: current_user.id, followed_id: user.id), method: :delete, remote: true) do |f| %>
      <%= f.hidden_field :follower_id %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "解除する", class: "btn btn-large btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6">
          <a class="profile"><%= profile_img(user) %></a>
          <%= link_to user.name, user_path(user.id) %>
          <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
          <%= render partial: 'follow_form', locals: {user: user} if signed_in? %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-1 col-md-4 col-sm-4">
      <div class="follow">
        <h3>ユーザー情報</h3>
        <p class="profile"><%= profile_img(@user) %></p>
        <p><%= @user.name %></p>
        <h4>BLOGS</h4>
        <% @user.blogs.each do |blog| %>
          <p><%= link_to blog.title, blog_path(blog.id) %></p>
        <% end %>
        <p><%= link_to '戻る', :back %></p>
      </div>
    </div>
    <div class="col-lg-3  col-md-4 col-sm-4">
      <div class="follow">
        <h3>FOLLOWING</h3>
        <% unless @user.followed_users.count == 0 %>
          <% @user.followed_users.each do |followed_user| %>
              <p class="profile"><%= profile_img(followed_user) %></p>
              <%= link_to followed_user.name, user_path(followed_user.id) %>
          <% end %>
        <% else %>
            <p>Not following anyone.</p>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-lg-offset-1 col-md-4 col-sm-4">
      <div class="follow">
        <h3>FOLLOWERS</h3>
        <% unless @user.followers.count == 0 %>
          <% @user.followers.each do |follower| %>
              <p class="profile"><%= profile_img(follower) %></p>
              <%= link_to follower.name, user_path(follower.id) %>
          <% end %>
        <% else %>
            <p>No followers.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>