config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  get 'notifications/index'

  resources :poems, only: [:index, :show]

  resources :my_page, only: [:index]

  root 'top#index'

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :tasks

  resources :submit_requests do
    get 'inbox', on: :collection
    member do
      patch 'approve'
      patch 'reject'
    end
  end

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  belongs_to :request_user, class_name: 'User'

  validates :user_id, :task_id, :request_user_id, presence: true
  validate :no_repeated_request, on: :create

  enum status: {依頼中: 1, 依頼済み: 2, 却下: 9}

  private
  def no_repeated_request
    submit_request = SubmitRequest.where(task_id: task_id, status: "依頼中")
    errors.add(:base, "このタスクは既に依頼を出しています") unless submit_request.blank?
  end

end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy, :approve, :reject]
  before_action :authenticate_user!

  # GET /submit_requests
  # GET /submit_requests.json
  def index
    @submit_requests = SubmitRequest.where(user_id: current_user.id)
  end

  def inbox
    @submit_requests = SubmitRequest.where(request_user_id: current_user.id)
  end

  # GET /submit_requests/1
  # GET /submit_requests/1.json
  def show
  end

  # GET /submit_requests/new
  def new
    @submit_request = current_user.submit_requests.build
  end

  # GET /submit_requests/1/edit
  def edit
  end

  # POST /submit_requests
  # POST /submit_requests.json
  def create
    @submit_request = current_user.submit_requests.build(submit_request_params)

    respond_to do |format|
      if @submit_request.save
        format.html { redirect_to @submit_request, notice: 'Submit request was successfully created.' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submit_requests/1
  # PATCH/PUT /submit_requests/1.json
  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        format.html { redirect_to @submit_request, notice: 'Submit request was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submit_requests/1
  # DELETE /submit_requests/1.json
  def destroy
    @submit_request.destroy
    respond_to do |format|
      format.html { redirect_to submit_requests_url, notice: 'Submit request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    if @submit_request.update(submit_request_params)
      @submit_request.task.update(charge_id: current_user.id)
      redirect_to inbox_submit_requests_path, notice: '依頼を承認しました'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作をおこなってください'
    end
  end

  def reject
    if @submit_request.update(submit_request_params)
      redirect_to inbox_submit_requests_path, notice: '依頼を却下しました'
    else
      redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作をおこなってください'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit_request
      @submit_request = SubmitRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_request_params
      params.require(:submit_request).permit(:user_id, :task_id, :message, :request_user_id, :status)
    end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
end

app/views/submit_requests/_form.html.erb
<%= form_for(@submit_request) do |f| %>
  <% if @submit_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit_request.errors.count, "error") %> prohibited this submit_request from being saved:</h2>

      <ul>
      <% @submit_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field :user_id %>
    
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.collection_select :task_id, Task.where(charge_id: current_user.id), :id, :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :request_user_id %><br>
    <%= f.collection_select :request_user_id, User.where.not(id: current_user.id), :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submit_requests/edit.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <h1>Editing Submit Request</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @submit_request %> |
    <%= link_to 'Back', submit_requests_path %>
  </div>
</div>

app/views/submit_requests/inbox.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <p id="notice"><%= notice %></p>

    <h1>Listing Submit Requests</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>User</th>
          <th>Task</th>
          <th>Message</th>
          <th>Request user</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @submit_requests.each do |submit_request| %>
          <tr>
            <td><%= submit_request.user.name %></td>
            <td><%= submit_request.task.title %></td>
            <td><%= submit_request.message %></td>
            <td><%= submit_request.request_user.name %></td>
            <td><%= submit_request.status %></td>
            <td><%= link_to '詳細', submit_request %></td>

            <td><%= link_to '承認', approve_submit_request_path(submit_request, submit_request: {status: "依頼済み"}), method: :patch, data: {confirm: "承認しますか？"} %></td>
            <td><%= link_to "拒否", reject_submit_request_path(submit_request, submit_request: {status: "却下"}), method: :patch, data: {confirm: "却下しますか？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Submit request', new_submit_request_path %>
  </div>
</div>

app/views/submit_requests/index.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <p id="notice"><%= notice %></p>

    <h1>Listing Submit Requests</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>User</th>
          <th>Task</th>
          <th>Message</th>
          <th>Request user</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @submit_requests.each do |submit_request| %>
          <tr>
            <td><%= submit_request.user.name %></td>
            <td><%= submit_request.task.title %></td>
            <td><%= submit_request.message %></td>
            <td><%= submit_request.request_user.name %></td>
            <td><%= submit_request.status %></td>
            <td><%= link_to 'show', submit_request %></td>
            <td><%= link_to 'Edit', edit_submit_request_path(submit_request) %></td>
            <td><%= link_to 'Delete', submit_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Submit request', new_submit_request_path %>
  </div>
</div>

app/views/submit_requests/new.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <h1>New Submit Request</h1>

    <%= render 'form' %>

    <%= link_to 'Back', submit_requests_path %>
  </div>
</div>

app/views/submit_requests/show.html.erb
<div class="container">
  <div class="wrapper col-md-10 col-md-offset-1 col-sm-10">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>User:</strong>
      <%= @submit_request.user.name %>
    </p>

    <p>
      <strong>Task:</strong>
      <%= @submit_request.task.title %>
    </p>

    <p>
      <strong>Message:</strong>
      <%= @submit_request.message %>
    </p>

    <p>
      <strong>Request user:</strong>
      <%= @submit_request.request_user.name %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @submit_request.status %>
    </p>

    <%= link_to 'Edit', edit_submit_request_path(@submit_request) %> |
    <%= link_to 'Back', submit_requests_path %>
  </div>
</div>